name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ master ] # Trigger the workflow on every push to the 'main' branch

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a Linux runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Check out your repository code

      - name: Setup Flutter
        uses: subosito/flutter-action@v2 # A popular action to set up Flutter
        with:
          channel: 'stable' # Use the stable channel of Flutter

      - name: Install dependencies
        run: flutter pub get # Get all the required Dart packages

      - name: Build Web app
        run: flutter build web --base-href /memeow/ # Build for web, setting the correct base href

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build/web' # Upload the built web files as an artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # The official deployment action
